[build]
  command = ""
  publish = "Output"

[build.environment]
	SWIFT_VERSION = ""  # Prevents Netlify from installing Swift
	NODE_VERSION = ""   # Ensures no Node.js is installed
	GO_VERSION = ""     # Stops Go installation