name: "Aleahim"
language: "en-US"
navigation:
  - label: "Home"
    url: "/"
  - label: "CV"
    url: "/cv/"
  - label: "Speaking"
    url: "/speaking/"
  - label: "Hire me"
    url: "https://codeweaver.info/"
    external: true
  - label: "About"
    url: "/about/"
